## A quick introduction to linear algebra in numpy

In [102]:
import numpy as np
# see https://numpy.org/doc/stable/reference/routines.linalg.html for documentation on linear algebra in numpy
import scipy.linalg as spla
# https://docs.scipy.org/doc/scipy/reference/linalg.html#
# numpy does not have support for all the linear algebra routines we may want to use; sometimes we need scipy.linalg

In [39]:
# Vectors in numpy are constructed by calling np.array() on a list of numbers:

x = np.array([1, 4, 7])
print(x)

# Adding vectors and scalar multiplication works as you would expect:

y = np.array([-3, 6, -3])
print(x + y)
print(3 * y)

# Elements of vectors are accessed via brackets. Python is 0-indexed, so the first element of x is given by x[0]
print(x[0])

[1 4 7]
[-2 10  4]
[-9 18 -9]
1


In [14]:
# The dot product and norm of vectors are easily calculated:

print(np.dot(x, y))

print(np.sqrt(np.dot(x, x)), np.linalg.norm(x))

0
8.12403840463596 8.12403840463596


In [40]:
# Matrices are constructed by calling np.array() on a list of lists. These are constructed row by row:

A = np.array([[1, 2], [3, 4]])
print(A)

B = np.array([[1, 2], [3, 4], [5, 6]])
print(B)

# Elements of matrix are accessed via brackets, with two indices - row first then column
# Recall python is 0-indexed, so the 1,2 element A_{12} is given by A[0, 1]
A[0, 1]

[[1 2]
 [3 4]]
[[1 2]
 [3 4]
 [5 6]]


2

In [24]:
# Adding matrices and multipling by scalars works as you'd expect:

C = np.array([[4, 8], [3, 5]])
print(A+C)
print(3.2 * A)

# If you try to add together two matrices with incompatible dimensions, numpy will throw an error
print(A+B)


[[ 5 10]
 [ 6  9]]
[[ 3.2  6.4]
 [ 9.6 12.8]]


ValueError: operands could not be broadcast together with shapes (2,2) (3,2) 

In [42]:
# We can check the various properties:

A = np.array([[1, 2], [3, 4]])
B = np.array([[4, 8], [3, 5]])
C = np.array([[7, 2], [3, 4]])

# Commutativity
print(A + B == B + A)
print(np.all(A + B == B + A))

# Associativity of matrix addition
print(np.all((A + B) + C == A + (B + C)))

# Associativity of scalar multiplication
print(np.all((3 * 4) * A == 3 * (4 * A)))

# Distributivity of matrix addition over scalar multiplcation
print(np.all(3 * (A + B) == 3 * A + 3 * B))

# Distributivity of scalar addition over scalar multiplication
print(np.all( (3 + 4) * A == 3 * A + 4 * A))


[[ True  True]
 [ True  True]]
True
True
True
True
True


In [43]:
# Taking transposes is done via the .T method

print(A)
print(A.T)

# For a symmetric matrix B, B = B.T
B = np.array([[1, 9], [9, 1]])
print(np.all(B == B.T))

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]
True


In [47]:
# Matrix multiplication is performed by the @ operator:

print(A)
print(B)
print(A @ B)

# Note the definition says that the ij-th element of AB should be the dot product of the ith row of A and the jth column of B. We can access these rows and columns using brackets, [], and slices, :.

# The 1-st row of A is given by A[0, :]; the second column of B by B[:, 1]
print(A[0, :])
print(B[:, 1])

# Lets check the 1,2 element of AB:
print((A @ B)[0, 1] == np.dot(A[0, :], B[:, 1]))


[[1 2]
 [3 4]]
[[1 9]
 [9 1]]
[[19 11]
 [39 31]]
[1 2]
[9 1]
True


In [49]:
# Matrices A, B provide an example that AB does not generally equal BA

AB = A@B
BA = B@A
print(AB)
print(BA)
print(np.any(AB == BA))

[[19 11]
 [39 31]]
[[28 38]
 [12 22]]
False


In [53]:
# We saw that another way to compute the dot product of two vectors x, y is to treat them as matrices and compute x'y. 

x.T @ y

0

In [62]:
# There are constructors for commonly used classes of matrices.

# Zero matrix:
O = np.zeros((3, 4))
print(O)

# Identity matrix:
I = np.eye(4)
print(I)

# Diagonal matrix:
D = np.diag(x)
print(x)
print(D)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[1 4 7]
[[1 0 0]
 [0 4 0]
 [0 0 7]]


In [79]:
# To invert a matrix we can use np.inv, provided it is of full rank

print(np.linalg.matrix_rank(np.array([[1, -1/2], [2, -1]]))) # not invertible - 2 x 2, but rank 1

print(np.linalg.matrix_rank(A))
print(np.linalg.inv(A))

print(np.linalg.inv(A) @ A)
# we see here that some (very small) numerical error has occured in the result of this calculation. This is inevitable when using computer arithmetic.

1
2
[[-2.   1. ]
 [ 1.5 -0.5]]
[[1.00000000e+00 0.00000000e+00]
 [1.11022302e-16 1.00000000e+00]]


In [78]:
# If solving a system of linear equations Ax = b, it is usually better to use

b = np.array([2, 7])
x = np.linalg.solve(A, b)
print(x)

# which solves the system using a matrix factorisation, as opposed to 

x = np.linalg.inv(A) @ b
print(x)

# which directly calculates the inverse. The former is usually faster and more accurate. (In this simple case both give the same solution).

[ 3.  -0.5]
[ 3.  -0.5]


In [109]:
# We can compute the principal square root of a positive (semi-)definite matrix
# This is an example where we need scipy.linalg

X = np.array([[2, 6, 3.2], [3,0, 9.3]])
A = X @ X.T
print(A) 

B = spla.sqrtm(A)
print(B) # B is symmetric
print(A - B @ B ) # correct up to numerical error

# Note that np does include np.sqrt - this is a function that operates elementwise, so we have 
C = np.sqrt(A) 
print(C)  # each C[i, j] is sqrt(A[i, j])

# but note that C is not a square root of A in the matrix sense
print(A - C@C)

[[50.24 35.76]
 [35.76 95.49]]
[[6.73816415 2.19935079]
 [2.19935079 9.52117934]]
[[-1.42108547e-14  0.00000000e+00]
 [ 0.00000000e+00 -1.42108547e-14]]
[[7.08801806 5.97996656]
 [5.97996656 9.77189848]]
[[-35.76       -65.06173705]
 [-65.06173705 -35.76      ]]


In [113]:
# The Cholesky decomposition is included in numpy
L = np.linalg.cholesky(A)
print(L)

print(L@L.T - A)

[[7.08801806 0.        ]
 [5.04513387 8.36878869]]
[[-7.10542736e-15  0.00000000e+00]
 [ 0.00000000e+00  1.42108547e-14]]


In [120]:
# The trace of a matrix can be caculated using np.trace
print(np.trace(A))

print(np.trace(A@B@C))
print(np.trace(B@C@A))
print(np.trace(C@A@B))

145.73000000000002
18003.479272926183
18003.479272926183
18003.479272926183
